@baseUrl = {{$dotenv baseUrl}}
@email = {{$dotenv email}}
@password = {{$dotenv password}}
@username = {{$dotenv username}}
@refreshToken = {{login.response.body.$.refreshToken}}
@accessToken = {{login.response.body.$.accessToken}}
{{$shared ACCESS_TOKEN}} = {{accessToken}}

###
# @name login
POST {{baseUrl}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name logout
POST {{baseUrl}}/api/auth/sign-out HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}

###
# @name verify
POST {{baseUrl}}/api/auth/verify-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}