@baseUrl = {{$dotenv baseUrl}}
@refreshToken = {{login.response.body.$.refreshToken}}
@accessToken = {{login.response.body.$.accessToken}}
{{$shared ACCESS_TOKEN}} = {{accessToken}}

###
# @name login
POST {{baseUrl}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "ed6c37c5-4f2c-11ef-ab8d-fc017cff3530@email.com",
  "password": "pass_ed6c37c5-4f2c-11ef-ab8d-fc017cff3530"
}

###
# @name logout
POST {{baseUrl}}/api/auth/sign-out HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}

###
# @name verify
POST {{baseUrl}}/api/auth/verify-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}