@baseUrl = {{$dotenv baseUrl}}
@accessToken = {{login.response.body.$.accessToken}}

###
# @name login
POST {{baseUrl}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "username": "user_487",
  "password": "pass_f2a2d8d0-3daa-4cff-96fe-44f146590878"
}

###
# @name create_page
POST {{baseUrl}}/api/page HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "About Page",
  "description": "About desc"
}

###
# @name get_by_slug
GET {{baseUrl}}/api/page/about-page HTTP/1.1
Content-Type: application/json
